// <auto-generated />
using Employee.DataAccessLayer.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeServices.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20210526103727_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Employee.DataAccessLayer.Employee", b =>
                {
                    b.Property<string>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = "0e446ba0-476c-4c16-918f-4dd35829a861",
                            Designation = "Consultant",
                            Doj = "02-Feb-2021",
                            Empcode = "1121055",
                            FirstName = "Shivendu",
                            LastName = "Srivastava",
                            LoginName = "shiv.sri"
                        },
                        new
                        {
                            EmployeeID = "b672dd42-b73f-4886-b499-fc7bff6f44d4",
                            Designation = "Sr. Business Analyst",
                            Doj = "08-Jun-2020",
                            Empcode = "1135109",
                            FirstName = "Kinjalk",
                            LastName = "Tripathi",
                            LoginName = "kinj.tri"
                        },
                        new
                        {
                            EmployeeID = "bbd718d8-b9b3-4f6c-adca-09b13327d920",
                            Designation = "Sr. Security Specialist",
                            Doj = "14-Apr-2019",
                            Empcode = "1156820",
                            FirstName = "Akrati",
                            LastName = "Bajpai",
                            LoginName = "akra.baj"
                        },
                        new
                        {
                            EmployeeID = "55b7e9d5-eaaa-4386-a5c4-259de5fd89b5",
                            Designation = "Sr. Finance Advisor",
                            Doj = "11-May-2015",
                            Empcode = "1135820",
                            FirstName = "Raghav",
                            LastName = "Gowda",
                            LoginName = "ragh.gow"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
