// <auto-generated />
using Employee.DataAccessLayer.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeServices.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Employee.DataAccessLayer.Employee", b =>
                {
                    b.Property<string>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = "52f1e8f9-70cb-40d2-8712-ce1c440c9fa8",
                            Designation = "Consultant",
                            Doj = "02-Feb-2021",
                            Empcode = "1121055",
                            FirstName = "Shivendu",
                            LastName = "Srivastava",
                            LoginName = "shiv.sri"
                        },
                        new
                        {
                            EmployeeID = "ae717a5b-cda2-410a-9484-a9b7460609c0",
                            Designation = "Sr. Business Analyst",
                            Doj = "08-Jun-2020",
                            Empcode = "1135109",
                            FirstName = "Kinjalk",
                            LastName = "Tripathi",
                            LoginName = "kinj.tri"
                        },
                        new
                        {
                            EmployeeID = "ac4ace0d-8d2e-4734-ba7f-93880c24d067",
                            Designation = "Sr. Security Specialist",
                            Doj = "14-Apr-2019",
                            Empcode = "1156820",
                            FirstName = "Akrati",
                            LastName = "Bajpai",
                            LoginName = "akra.baj"
                        },
                        new
                        {
                            EmployeeID = "dec7e46e-8c09-4c01-a7a3-694ed60a91ad",
                            Designation = "Sr. Finance Advisor",
                            Doj = "11-May-2015",
                            Empcode = "1135820",
                            FirstName = "Raghav",
                            LastName = "Gowda",
                            LoginName = "ragh.gow"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
